import turtle
screen = turtle.Screen()
turtle.colormode(255)
turtle.mode("logo")
Tuples = ()
MyVeryOwnShape_turtle = turtle.Turtle()
MyVeryOwnShape_turtle.color(0, 0, 0)
screen.register_shape("MyVeryOwnShape", Tuples)
MyVeryOwnShape_turtle.shape("MyVeryOwnShape")
turtle.mainloop()